// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/authentication"
	"backend/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthenticationCreate is the builder for creating a Authentication entity.
type AuthenticationCreate struct {
	config
	mutation *AuthenticationMutation
	hooks    []Hook
}

// SetSessionID sets the "session_id" field.
func (ac *AuthenticationCreate) SetSessionID(s string) *AuthenticationCreate {
	ac.mutation.SetSessionID(s)
	return ac
}

// SetUserID sets the "user_id" field.
func (ac *AuthenticationCreate) SetUserID(i int) *AuthenticationCreate {
	ac.mutation.SetUserID(i)
	return ac
}

// SetLoginTime sets the "login_time" field.
func (ac *AuthenticationCreate) SetLoginTime(t time.Time) *AuthenticationCreate {
	ac.mutation.SetLoginTime(t)
	return ac
}

// SetNillableLoginTime sets the "login_time" field if the given value is not nil.
func (ac *AuthenticationCreate) SetNillableLoginTime(t *time.Time) *AuthenticationCreate {
	if t != nil {
		ac.SetLoginTime(*t)
	}
	return ac
}

// SetLogoutTime sets the "logout_time" field.
func (ac *AuthenticationCreate) SetLogoutTime(t time.Time) *AuthenticationCreate {
	ac.mutation.SetLogoutTime(t)
	return ac
}

// SetNillableLogoutTime sets the "logout_time" field if the given value is not nil.
func (ac *AuthenticationCreate) SetNillableLogoutTime(t *time.Time) *AuthenticationCreate {
	if t != nil {
		ac.SetLogoutTime(*t)
	}
	return ac
}

// SetUserOwnerID sets the "userOwner" edge to the User entity by ID.
func (ac *AuthenticationCreate) SetUserOwnerID(id int) *AuthenticationCreate {
	ac.mutation.SetUserOwnerID(id)
	return ac
}

// SetNillableUserOwnerID sets the "userOwner" edge to the User entity by ID if the given value is not nil.
func (ac *AuthenticationCreate) SetNillableUserOwnerID(id *int) *AuthenticationCreate {
	if id != nil {
		ac = ac.SetUserOwnerID(*id)
	}
	return ac
}

// SetUserOwner sets the "userOwner" edge to the User entity.
func (ac *AuthenticationCreate) SetUserOwner(u *User) *AuthenticationCreate {
	return ac.SetUserOwnerID(u.ID)
}

// Mutation returns the AuthenticationMutation object of the builder.
func (ac *AuthenticationCreate) Mutation() *AuthenticationMutation {
	return ac.mutation
}

// Save creates the Authentication in the database.
func (ac *AuthenticationCreate) Save(ctx context.Context) (*Authentication, error) {
	ac.defaults()
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AuthenticationCreate) SaveX(ctx context.Context) *Authentication {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AuthenticationCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AuthenticationCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AuthenticationCreate) defaults() {
	if _, ok := ac.mutation.LoginTime(); !ok {
		v := authentication.DefaultLoginTime()
		ac.mutation.SetLoginTime(v)
	}
	if _, ok := ac.mutation.LogoutTime(); !ok {
		v := authentication.DefaultLogoutTime()
		ac.mutation.SetLogoutTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AuthenticationCreate) check() error {
	if _, ok := ac.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "Authentication.session_id"`)}
	}
	if v, ok := ac.mutation.SessionID(); ok {
		if err := authentication.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "Authentication.session_id": %w`, err)}
		}
	}
	if _, ok := ac.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Authentication.user_id"`)}
	}
	if _, ok := ac.mutation.LoginTime(); !ok {
		return &ValidationError{Name: "login_time", err: errors.New(`ent: missing required field "Authentication.login_time"`)}
	}
	if _, ok := ac.mutation.LogoutTime(); !ok {
		return &ValidationError{Name: "logout_time", err: errors.New(`ent: missing required field "Authentication.logout_time"`)}
	}
	return nil
}

func (ac *AuthenticationCreate) sqlSave(ctx context.Context) (*Authentication, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AuthenticationCreate) createSpec() (*Authentication, *sqlgraph.CreateSpec) {
	var (
		_node = &Authentication{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(authentication.Table, sqlgraph.NewFieldSpec(authentication.FieldID, field.TypeInt))
	)
	if value, ok := ac.mutation.SessionID(); ok {
		_spec.SetField(authentication.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := ac.mutation.UserID(); ok {
		_spec.SetField(authentication.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := ac.mutation.LoginTime(); ok {
		_spec.SetField(authentication.FieldLoginTime, field.TypeTime, value)
		_node.LoginTime = value
	}
	if value, ok := ac.mutation.LogoutTime(); ok {
		_spec.SetField(authentication.FieldLogoutTime, field.TypeTime, value)
		_node.LogoutTime = value
	}
	if nodes := ac.mutation.UserOwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authentication.UserOwnerTable,
			Columns: []string{authentication.UserOwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node._User_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AuthenticationCreateBulk is the builder for creating many Authentication entities in bulk.
type AuthenticationCreateBulk struct {
	config
	err      error
	builders []*AuthenticationCreate
}

// Save creates the Authentication entities in the database.
func (acb *AuthenticationCreateBulk) Save(ctx context.Context) ([]*Authentication, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Authentication, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthenticationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AuthenticationCreateBulk) SaveX(ctx context.Context) []*Authentication {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AuthenticationCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AuthenticationCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
