// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/predicate"
	"backend/ent/settings"
	"backend/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SettingsUpdate is the builder for updating Settings entities.
type SettingsUpdate struct {
	config
	hooks    []Hook
	mutation *SettingsMutation
}

// Where appends a list predicates to the SettingsUpdate builder.
func (su *SettingsUpdate) Where(ps ...predicate.Settings) *SettingsUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetUserID sets the "user_id" field.
func (su *SettingsUpdate) SetUserID(i int) *SettingsUpdate {
	su.mutation.ResetUserID()
	su.mutation.SetUserID(i)
	return su
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableUserID(i *int) *SettingsUpdate {
	if i != nil {
		su.SetUserID(*i)
	}
	return su
}

// AddUserID adds i to the "user_id" field.
func (su *SettingsUpdate) AddUserID(i int) *SettingsUpdate {
	su.mutation.AddUserID(i)
	return su
}

// SetLoginTime sets the "login_time" field.
func (su *SettingsUpdate) SetLoginTime(t time.Time) *SettingsUpdate {
	su.mutation.SetLoginTime(t)
	return su
}

// SetNillableLoginTime sets the "login_time" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableLoginTime(t *time.Time) *SettingsUpdate {
	if t != nil {
		su.SetLoginTime(*t)
	}
	return su
}

// SetLogoutTime sets the "logout_time" field.
func (su *SettingsUpdate) SetLogoutTime(t time.Time) *SettingsUpdate {
	su.mutation.SetLogoutTime(t)
	return su
}

// SetNillableLogoutTime sets the "logout_time" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableLogoutTime(t *time.Time) *SettingsUpdate {
	if t != nil {
		su.SetLogoutTime(*t)
	}
	return su
}

// SetUserOwnerID sets the "userOwner" edge to the User entity by ID.
func (su *SettingsUpdate) SetUserOwnerID(id int) *SettingsUpdate {
	su.mutation.SetUserOwnerID(id)
	return su
}

// SetUserOwner sets the "userOwner" edge to the User entity.
func (su *SettingsUpdate) SetUserOwner(u *User) *SettingsUpdate {
	return su.SetUserOwnerID(u.ID)
}

// Mutation returns the SettingsMutation object of the builder.
func (su *SettingsUpdate) Mutation() *SettingsMutation {
	return su.mutation
}

// ClearUserOwner clears the "userOwner" edge to the User entity.
func (su *SettingsUpdate) ClearUserOwner() *SettingsUpdate {
	su.mutation.ClearUserOwner()
	return su
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SettingsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SettingsUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SettingsUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SettingsUpdate) check() error {
	if _, ok := su.mutation.UserOwnerID(); su.mutation.UserOwnerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Settings.userOwner"`)
	}
	return nil
}

func (su *SettingsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.UserID(); ok {
		_spec.SetField(settings.FieldUserID, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedUserID(); ok {
		_spec.AddField(settings.FieldUserID, field.TypeInt, value)
	}
	if value, ok := su.mutation.LoginTime(); ok {
		_spec.SetField(settings.FieldLoginTime, field.TypeTime, value)
	}
	if value, ok := su.mutation.LogoutTime(); ok {
		_spec.SetField(settings.FieldLogoutTime, field.TypeTime, value)
	}
	if su.mutation.UserOwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   settings.UserOwnerTable,
			Columns: []string{settings.UserOwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.UserOwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   settings.UserOwnerTable,
			Columns: []string{settings.UserOwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SettingsUpdateOne is the builder for updating a single Settings entity.
type SettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SettingsMutation
}

// SetUserID sets the "user_id" field.
func (suo *SettingsUpdateOne) SetUserID(i int) *SettingsUpdateOne {
	suo.mutation.ResetUserID()
	suo.mutation.SetUserID(i)
	return suo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableUserID(i *int) *SettingsUpdateOne {
	if i != nil {
		suo.SetUserID(*i)
	}
	return suo
}

// AddUserID adds i to the "user_id" field.
func (suo *SettingsUpdateOne) AddUserID(i int) *SettingsUpdateOne {
	suo.mutation.AddUserID(i)
	return suo
}

// SetLoginTime sets the "login_time" field.
func (suo *SettingsUpdateOne) SetLoginTime(t time.Time) *SettingsUpdateOne {
	suo.mutation.SetLoginTime(t)
	return suo
}

// SetNillableLoginTime sets the "login_time" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableLoginTime(t *time.Time) *SettingsUpdateOne {
	if t != nil {
		suo.SetLoginTime(*t)
	}
	return suo
}

// SetLogoutTime sets the "logout_time" field.
func (suo *SettingsUpdateOne) SetLogoutTime(t time.Time) *SettingsUpdateOne {
	suo.mutation.SetLogoutTime(t)
	return suo
}

// SetNillableLogoutTime sets the "logout_time" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableLogoutTime(t *time.Time) *SettingsUpdateOne {
	if t != nil {
		suo.SetLogoutTime(*t)
	}
	return suo
}

// SetUserOwnerID sets the "userOwner" edge to the User entity by ID.
func (suo *SettingsUpdateOne) SetUserOwnerID(id int) *SettingsUpdateOne {
	suo.mutation.SetUserOwnerID(id)
	return suo
}

// SetUserOwner sets the "userOwner" edge to the User entity.
func (suo *SettingsUpdateOne) SetUserOwner(u *User) *SettingsUpdateOne {
	return suo.SetUserOwnerID(u.ID)
}

// Mutation returns the SettingsMutation object of the builder.
func (suo *SettingsUpdateOne) Mutation() *SettingsMutation {
	return suo.mutation
}

// ClearUserOwner clears the "userOwner" edge to the User entity.
func (suo *SettingsUpdateOne) ClearUserOwner() *SettingsUpdateOne {
	suo.mutation.ClearUserOwner()
	return suo
}

// Where appends a list predicates to the SettingsUpdate builder.
func (suo *SettingsUpdateOne) Where(ps ...predicate.Settings) *SettingsUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SettingsUpdateOne) Select(field string, fields ...string) *SettingsUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Settings entity.
func (suo *SettingsUpdateOne) Save(ctx context.Context) (*Settings, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SettingsUpdateOne) SaveX(ctx context.Context) *Settings {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SettingsUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SettingsUpdateOne) check() error {
	if _, ok := suo.mutation.UserOwnerID(); suo.mutation.UserOwnerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Settings.userOwner"`)
	}
	return nil
}

func (suo *SettingsUpdateOne) sqlSave(ctx context.Context) (_node *Settings, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Settings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, settings.FieldID)
		for _, f := range fields {
			if !settings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != settings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.UserID(); ok {
		_spec.SetField(settings.FieldUserID, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedUserID(); ok {
		_spec.AddField(settings.FieldUserID, field.TypeInt, value)
	}
	if value, ok := suo.mutation.LoginTime(); ok {
		_spec.SetField(settings.FieldLoginTime, field.TypeTime, value)
	}
	if value, ok := suo.mutation.LogoutTime(); ok {
		_spec.SetField(settings.FieldLogoutTime, field.TypeTime, value)
	}
	if suo.mutation.UserOwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   settings.UserOwnerTable,
			Columns: []string{settings.UserOwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.UserOwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   settings.UserOwnerTable,
			Columns: []string{settings.UserOwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Settings{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
