// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/category"
	"backend/ent/comment"
	"backend/ent/project"
	"backend/ent/task"
	"backend/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskCreate is the builder for creating a Task entity.
type TaskCreate struct {
	config
	mutation *TaskMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (tc *TaskCreate) SetTitle(s string) *TaskCreate {
	tc.mutation.SetTitle(s)
	return tc
}

// SetDescription sets the "description" field.
func (tc *TaskCreate) SetDescription(s string) *TaskCreate {
	tc.mutation.SetDescription(s)
	return tc
}

// SetDueDate sets the "due_date" field.
func (tc *TaskCreate) SetDueDate(t time.Time) *TaskCreate {
	tc.mutation.SetDueDate(t)
	return tc
}

// SetStatus sets the "status" field.
func (tc *TaskCreate) SetStatus(s string) *TaskCreate {
	tc.mutation.SetStatus(s)
	return tc
}

// SetPiority sets the "piority" field.
func (tc *TaskCreate) SetPiority(s string) *TaskCreate {
	tc.mutation.SetPiority(s)
	return tc
}

// SetTags sets the "tags" field.
func (tc *TaskCreate) SetTags(s string) *TaskCreate {
	tc.mutation.SetTags(s)
	return tc
}

// SetProjectID sets the "project_id" field.
func (tc *TaskCreate) SetProjectID(s string) *TaskCreate {
	tc.mutation.SetProjectID(s)
	return tc
}

// SetCategoryID sets the "category_id" field.
func (tc *TaskCreate) SetCategoryID(s string) *TaskCreate {
	tc.mutation.SetCategoryID(s)
	return tc
}

// SetComments sets the "comments" field.
func (tc *TaskCreate) SetComments(s string) *TaskCreate {
	tc.mutation.SetComments(s)
	return tc
}

// SetCreatedAt sets the "created_at" field.
func (tc *TaskCreate) SetCreatedAt(t time.Time) *TaskCreate {
	tc.mutation.SetCreatedAt(t)
	return tc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tc *TaskCreate) SetNillableCreatedAt(t *time.Time) *TaskCreate {
	if t != nil {
		tc.SetCreatedAt(*t)
	}
	return tc
}

// SetUpdateAt sets the "update_at" field.
func (tc *TaskCreate) SetUpdateAt(t time.Time) *TaskCreate {
	tc.mutation.SetUpdateAt(t)
	return tc
}

// SetUserOwnerID sets the "userOwner" edge to the User entity by ID.
func (tc *TaskCreate) SetUserOwnerID(id int) *TaskCreate {
	tc.mutation.SetUserOwnerID(id)
	return tc
}

// SetNillableUserOwnerID sets the "userOwner" edge to the User entity by ID if the given value is not nil.
func (tc *TaskCreate) SetNillableUserOwnerID(id *int) *TaskCreate {
	if id != nil {
		tc = tc.SetUserOwnerID(*id)
	}
	return tc
}

// SetUserOwner sets the "userOwner" edge to the User entity.
func (tc *TaskCreate) SetUserOwner(u *User) *TaskCreate {
	return tc.SetUserOwnerID(u.ID)
}

// SetProjectOwnerID sets the "projectOwner" edge to the Project entity by ID.
func (tc *TaskCreate) SetProjectOwnerID(id int) *TaskCreate {
	tc.mutation.SetProjectOwnerID(id)
	return tc
}

// SetNillableProjectOwnerID sets the "projectOwner" edge to the Project entity by ID if the given value is not nil.
func (tc *TaskCreate) SetNillableProjectOwnerID(id *int) *TaskCreate {
	if id != nil {
		tc = tc.SetProjectOwnerID(*id)
	}
	return tc
}

// SetProjectOwner sets the "projectOwner" edge to the Project entity.
func (tc *TaskCreate) SetProjectOwner(p *Project) *TaskCreate {
	return tc.SetProjectOwnerID(p.ID)
}

// AddCommentIDs adds the "comment" edge to the Comment entity by IDs.
func (tc *TaskCreate) AddCommentIDs(ids ...int) *TaskCreate {
	tc.mutation.AddCommentIDs(ids...)
	return tc
}

// AddComment adds the "comment" edges to the Comment entity.
func (tc *TaskCreate) AddComment(c ...*Comment) *TaskCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return tc.AddCommentIDs(ids...)
}

// SetCategoryOwnerID sets the "categoryOwner" edge to the Category entity by ID.
func (tc *TaskCreate) SetCategoryOwnerID(id int) *TaskCreate {
	tc.mutation.SetCategoryOwnerID(id)
	return tc
}

// SetNillableCategoryOwnerID sets the "categoryOwner" edge to the Category entity by ID if the given value is not nil.
func (tc *TaskCreate) SetNillableCategoryOwnerID(id *int) *TaskCreate {
	if id != nil {
		tc = tc.SetCategoryOwnerID(*id)
	}
	return tc
}

// SetCategoryOwner sets the "categoryOwner" edge to the Category entity.
func (tc *TaskCreate) SetCategoryOwner(c *Category) *TaskCreate {
	return tc.SetCategoryOwnerID(c.ID)
}

// Mutation returns the TaskMutation object of the builder.
func (tc *TaskCreate) Mutation() *TaskMutation {
	return tc.mutation
}

// Save creates the Task in the database.
func (tc *TaskCreate) Save(ctx context.Context) (*Task, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TaskCreate) SaveX(ctx context.Context) *Task {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TaskCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TaskCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TaskCreate) defaults() {
	if _, ok := tc.mutation.CreatedAt(); !ok {
		v := task.DefaultCreatedAt()
		tc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TaskCreate) check() error {
	if _, ok := tc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Task.title"`)}
	}
	if v, ok := tc.mutation.Title(); ok {
		if err := task.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Task.title": %w`, err)}
		}
	}
	if _, ok := tc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Task.description"`)}
	}
	if _, ok := tc.mutation.DueDate(); !ok {
		return &ValidationError{Name: "due_date", err: errors.New(`ent: missing required field "Task.due_date"`)}
	}
	if _, ok := tc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Task.status"`)}
	}
	if _, ok := tc.mutation.Piority(); !ok {
		return &ValidationError{Name: "piority", err: errors.New(`ent: missing required field "Task.piority"`)}
	}
	if _, ok := tc.mutation.Tags(); !ok {
		return &ValidationError{Name: "tags", err: errors.New(`ent: missing required field "Task.tags"`)}
	}
	if _, ok := tc.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "Task.project_id"`)}
	}
	if _, ok := tc.mutation.CategoryID(); !ok {
		return &ValidationError{Name: "category_id", err: errors.New(`ent: missing required field "Task.category_id"`)}
	}
	if _, ok := tc.mutation.Comments(); !ok {
		return &ValidationError{Name: "comments", err: errors.New(`ent: missing required field "Task.comments"`)}
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Task.created_at"`)}
	}
	if _, ok := tc.mutation.UpdateAt(); !ok {
		return &ValidationError{Name: "update_at", err: errors.New(`ent: missing required field "Task.update_at"`)}
	}
	return nil
}

func (tc *TaskCreate) sqlSave(ctx context.Context) (*Task, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TaskCreate) createSpec() (*Task, *sqlgraph.CreateSpec) {
	var (
		_node = &Task{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(task.Table, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt))
	)
	if value, ok := tc.mutation.Title(); ok {
		_spec.SetField(task.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := tc.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := tc.mutation.DueDate(); ok {
		_spec.SetField(task.FieldDueDate, field.TypeTime, value)
		_node.DueDate = value
	}
	if value, ok := tc.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := tc.mutation.Piority(); ok {
		_spec.SetField(task.FieldPiority, field.TypeString, value)
		_node.Piority = value
	}
	if value, ok := tc.mutation.Tags(); ok {
		_spec.SetField(task.FieldTags, field.TypeString, value)
		_node.Tags = value
	}
	if value, ok := tc.mutation.ProjectID(); ok {
		_spec.SetField(task.FieldProjectID, field.TypeString, value)
		_node.ProjectID = value
	}
	if value, ok := tc.mutation.CategoryID(); ok {
		_spec.SetField(task.FieldCategoryID, field.TypeString, value)
		_node.CategoryID = value
	}
	if value, ok := tc.mutation.Comments(); ok {
		_spec.SetField(task.FieldComments, field.TypeString, value)
		_node.Comments = value
	}
	if value, ok := tc.mutation.CreatedAt(); ok {
		_spec.SetField(task.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tc.mutation.UpdateAt(); ok {
		_spec.SetField(task.FieldUpdateAt, field.TypeTime, value)
		_node.UpdateAt = value
	}
	if nodes := tc.mutation.UserOwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.UserOwnerTable,
			Columns: []string{task.UserOwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node._User_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.ProjectOwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ProjectOwnerTable,
			Columns: []string{task.ProjectOwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node._Project_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.CommentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommentTable,
			Columns: []string{task.CommentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.CategoryOwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.CategoryOwnerTable,
			Columns: []string{task.CategoryOwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node._Category_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskCreateBulk is the builder for creating many Task entities in bulk.
type TaskCreateBulk struct {
	config
	err      error
	builders []*TaskCreate
}

// Save creates the Task entities in the database.
func (tcb *TaskCreateBulk) Save(ctx context.Context) ([]*Task, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Task, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TaskCreateBulk) SaveX(ctx context.Context) []*Task {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TaskCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TaskCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
